default:
  image: python:3.8.13-alpine3.16

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Poetry installs the virtual environment in .venv if specified
cache:
  paths:
    - .cache/pip
    - .venv/

before_script:
  - export PYTHONIOENCODING=utf-8
  - export PATH=$PATH:/home/gitlab-runner/.local/bin
  - python3 -m pip install poetry
  - poetry config virtualenvs.in-project true
  - poetry install

stages:
  - quality gate
  - warnings
  - build and publish

black:
  stage: quality gate
  script:
    - poetry run black --check .

prospector_low:
  stage: quality gate
  script:
    - poetry run prospector --strictness low .

test_all:
  stage: quality gate
  script:
    - poetry run pytest --junitxml=junit.xml
  artifacts:
    reports:
      junit: junit.xml

coverage:
  stage: warnings
  allow_failure: true
  script:
    - poetry run coverage run -m pytest
    - poetry run coverage report
    - poetry run coverage xml
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

prospector:
  stage: warnings
  allow_failure: true
  script:
    - poetry run prospector

isort:
  stage: warnings
  allow_failure: true
  script:
    - poetry run isort . --check-only --profile black

build_and_publish:
  stage: build and publish
  needs:
    - test_all
  only:
    - deploy
  script:
    - poetry config --local repositories.lrz-gitlab
      "https://gitlab.lrz.de/api/v4/projects/${CI_PROJECT_ID}/packages/pypi"
    - poetry build
    - poetry publish --repository lrz-gitlab --username gitlab-ci-token --password $CI_JOB_TOKEN

docker:
  stage: build and publish
  needs:
    - test_all
  only:
    - deploy
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t gitlab.lrz.de:5005/pypracticum/incentive-mechanism . -f Dockerfile.prod
    - docker push gitlab.lrz.de:5005/pypracticum/incentive-mechanism
