FROM python:3.8-slim

# python
ENV PYTHONUNBUFFERED=1
# pip:
ENV PIP_NO_CACHE_DIR=1
ENV PIP_DISABLE_PIP_VERSION_CHECK=1
ENV PIP_DEFAULT_TIMEOUT=100
# poetry:
ENV POETRY_NO_INTERACTION=1

WORKDIR /incentive-mechanism

RUN pip install "poetry>=1.1.13,<2.0.0"

COPY poetry.lock pyproject.toml ./

RUN poetry install --no-ansi

COPY executables executables
COPY agatha agatha
COPY data data

CMD ["poetry", "run", "python", "executables/run-agatha.py", "--host", "0.0.0.0"]
